// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ritsec/ops-bot-iii/ent/openstack"
	"github.com/ritsec/ops-bot-iii/ent/user"
)

// OpenstackCreate is the builder for creating a Openstack entity.
type OpenstackCreate struct {
	config
	mutation *OpenstackMutation
	hooks    []Hook
}

// SetTimestamp sets the "timestamp" field.
func (oc *OpenstackCreate) SetTimestamp(t time.Time) *OpenstackCreate {
	oc.mutation.SetTimestamp(t)
	return oc
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (oc *OpenstackCreate) SetNillableTimestamp(t *time.Time) *OpenstackCreate {
	if t != nil {
		oc.SetTimestamp(*t)
	}
	return oc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (oc *OpenstackCreate) SetUserID(id string) *OpenstackCreate {
	oc.mutation.SetUserID(id)
	return oc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (oc *OpenstackCreate) SetNillableUserID(id *string) *OpenstackCreate {
	if id != nil {
		oc = oc.SetUserID(*id)
	}
	return oc
}

// SetUser sets the "user" edge to the User entity.
func (oc *OpenstackCreate) SetUser(u *User) *OpenstackCreate {
	return oc.SetUserID(u.ID)
}

// Mutation returns the OpenstackMutation object of the builder.
func (oc *OpenstackCreate) Mutation() *OpenstackMutation {
	return oc.mutation
}

// Save creates the Openstack in the database.
func (oc *OpenstackCreate) Save(ctx context.Context) (*Openstack, error) {
	oc.defaults()
	return withHooks(ctx, oc.sqlSave, oc.mutation, oc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OpenstackCreate) SaveX(ctx context.Context) *Openstack {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OpenstackCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OpenstackCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oc *OpenstackCreate) defaults() {
	if _, ok := oc.mutation.Timestamp(); !ok {
		v := openstack.DefaultTimestamp()
		oc.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oc *OpenstackCreate) check() error {
	if _, ok := oc.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "Openstack.timestamp"`)}
	}
	return nil
}

func (oc *OpenstackCreate) sqlSave(ctx context.Context) (*Openstack, error) {
	if err := oc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	oc.mutation.id = &_node.ID
	oc.mutation.done = true
	return _node, nil
}

func (oc *OpenstackCreate) createSpec() (*Openstack, *sqlgraph.CreateSpec) {
	var (
		_node = &Openstack{config: oc.config}
		_spec = sqlgraph.NewCreateSpec(openstack.Table, sqlgraph.NewFieldSpec(openstack.FieldID, field.TypeInt))
	)
	if value, ok := oc.mutation.Timestamp(); ok {
		_spec.SetField(openstack.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if nodes := oc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   openstack.UserTable,
			Columns: []string{openstack.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_openstack = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OpenstackCreateBulk is the builder for creating many Openstack entities in bulk.
type OpenstackCreateBulk struct {
	config
	err      error
	builders []*OpenstackCreate
}

// Save creates the Openstack entities in the database.
func (ocb *OpenstackCreateBulk) Save(ctx context.Context) ([]*Openstack, error) {
	if ocb.err != nil {
		return nil, ocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*Openstack, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpenstackMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OpenstackCreateBulk) SaveX(ctx context.Context) []*Openstack {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OpenstackCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OpenstackCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}
