// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ritsec/ops-bot-iii/ent/schema"
	"github.com/ritsec/ops-bot-iii/ent/signin"
	"github.com/ritsec/ops-bot-iii/ent/user"
	"github.com/ritsec/ops-bot-iii/ent/vote"
	"github.com/ritsec/ops-bot-iii/ent/voteresult"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	signinFields := schema.Signin{}.Fields()
	_ = signinFields
	// signinDescTimestamp is the schema descriptor for timestamp field.
	signinDescTimestamp := signinFields[0].Descriptor()
	// signin.DefaultTimestamp holds the default value on creation for the timestamp field.
	signin.DefaultTimestamp = signinDescTimestamp.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// userDescVerificationAttempts is the schema descriptor for verification_attempts field.
	userDescVerificationAttempts := userFields[2].Descriptor()
	// user.DefaultVerificationAttempts holds the default value on creation for the verification_attempts field.
	user.DefaultVerificationAttempts = userDescVerificationAttempts.Default.(int8)
	// user.VerificationAttemptsValidator is a validator for the "verification_attempts" field. It is called by the builders before save.
	user.VerificationAttemptsValidator = userDescVerificationAttempts.Validators[0].(func(int8) error)
	// userDescVerified is the schema descriptor for verified field.
	userDescVerified := userFields[3].Descriptor()
	// user.DefaultVerified holds the default value on creation for the verified field.
	user.DefaultVerified = userDescVerified.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
	voteFields := schema.Vote{}.Fields()
	_ = voteFields
	// voteDescSelection is the schema descriptor for selection field.
	voteDescSelection := voteFields[0].Descriptor()
	// vote.SelectionValidator is a validator for the "selection" field. It is called by the builders before save.
	vote.SelectionValidator = voteDescSelection.Validators[0].(func(string) error)
	// voteDescRank is the schema descriptor for rank field.
	voteDescRank := voteFields[1].Descriptor()
	// vote.RankValidator is a validator for the "rank" field. It is called by the builders before save.
	vote.RankValidator = voteDescRank.Validators[0].(func(int) error)
	// voteDescVoteID is the schema descriptor for vote_id field.
	voteDescVoteID := voteFields[2].Descriptor()
	// vote.VoteIDValidator is a validator for the "vote_id" field. It is called by the builders before save.
	vote.VoteIDValidator = voteDescVoteID.Validators[0].(func(string) error)
	voteresultFields := schema.VoteResult{}.Fields()
	_ = voteresultFields
	// voteresultDescVoteID is the schema descriptor for vote_id field.
	voteresultDescVoteID := voteresultFields[2].Descriptor()
	// voteresult.VoteIDValidator is a validator for the "vote_id" field. It is called by the builders before save.
	voteresult.VoteIDValidator = voteresultDescVoteID.Validators[0].(func(string) error)
}
