// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ritsec/ops-bot-iii/ent/predicate"
	"github.com/ritsec/ops-bot-iii/ent/shitposts"
	"github.com/ritsec/ops-bot-iii/ent/user"
)

// ShitpostsUpdate is the builder for updating Shitposts entities.
type ShitpostsUpdate struct {
	config
	hooks    []Hook
	mutation *ShitpostsMutation
}

// Where appends a list predicates to the ShitpostsUpdate builder.
func (su *ShitpostsUpdate) Where(ps ...predicate.Shitposts) *ShitpostsUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetCount sets the "count" field.
func (su *ShitpostsUpdate) SetCount(i int) *ShitpostsUpdate {
	su.mutation.ResetCount()
	su.mutation.SetCount(i)
	return su
}

// AddCount adds i to the "count" field.
func (su *ShitpostsUpdate) AddCount(i int) *ShitpostsUpdate {
	su.mutation.AddCount(i)
	return su
}

// SetUserID sets the "user" edge to the User entity by ID.
func (su *ShitpostsUpdate) SetUserID(id string) *ShitpostsUpdate {
	su.mutation.SetUserID(id)
	return su
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (su *ShitpostsUpdate) SetNillableUserID(id *string) *ShitpostsUpdate {
	if id != nil {
		su = su.SetUserID(*id)
	}
	return su
}

// SetUser sets the "user" edge to the User entity.
func (su *ShitpostsUpdate) SetUser(u *User) *ShitpostsUpdate {
	return su.SetUserID(u.ID)
}

// Mutation returns the ShitpostsMutation object of the builder.
func (su *ShitpostsUpdate) Mutation() *ShitpostsMutation {
	return su.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (su *ShitpostsUpdate) ClearUser() *ShitpostsUpdate {
	su.mutation.ClearUser()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *ShitpostsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, ShitpostsMutation](ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *ShitpostsUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ShitpostsUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ShitpostsUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *ShitpostsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(shitposts.Table, shitposts.Columns, sqlgraph.NewFieldSpec(shitposts.FieldID, field.TypeString))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Count(); ok {
		_spec.SetField(shitposts.FieldCount, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedCount(); ok {
		_spec.AddField(shitposts.FieldCount, field.TypeInt, value)
	}
	if su.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shitposts.UserTable,
			Columns: []string{shitposts.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shitposts.UserTable,
			Columns: []string{shitposts.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shitposts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// ShitpostsUpdateOne is the builder for updating a single Shitposts entity.
type ShitpostsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShitpostsMutation
}

// SetCount sets the "count" field.
func (suo *ShitpostsUpdateOne) SetCount(i int) *ShitpostsUpdateOne {
	suo.mutation.ResetCount()
	suo.mutation.SetCount(i)
	return suo
}

// AddCount adds i to the "count" field.
func (suo *ShitpostsUpdateOne) AddCount(i int) *ShitpostsUpdateOne {
	suo.mutation.AddCount(i)
	return suo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (suo *ShitpostsUpdateOne) SetUserID(id string) *ShitpostsUpdateOne {
	suo.mutation.SetUserID(id)
	return suo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (suo *ShitpostsUpdateOne) SetNillableUserID(id *string) *ShitpostsUpdateOne {
	if id != nil {
		suo = suo.SetUserID(*id)
	}
	return suo
}

// SetUser sets the "user" edge to the User entity.
func (suo *ShitpostsUpdateOne) SetUser(u *User) *ShitpostsUpdateOne {
	return suo.SetUserID(u.ID)
}

// Mutation returns the ShitpostsMutation object of the builder.
func (suo *ShitpostsUpdateOne) Mutation() *ShitpostsMutation {
	return suo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (suo *ShitpostsUpdateOne) ClearUser() *ShitpostsUpdateOne {
	suo.mutation.ClearUser()
	return suo
}

// Where appends a list predicates to the ShitpostsUpdate builder.
func (suo *ShitpostsUpdateOne) Where(ps ...predicate.Shitposts) *ShitpostsUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *ShitpostsUpdateOne) Select(field string, fields ...string) *ShitpostsUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Shitposts entity.
func (suo *ShitpostsUpdateOne) Save(ctx context.Context) (*Shitposts, error) {
	return withHooks[*Shitposts, ShitpostsMutation](ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ShitpostsUpdateOne) SaveX(ctx context.Context) *Shitposts {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *ShitpostsUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ShitpostsUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *ShitpostsUpdateOne) sqlSave(ctx context.Context) (_node *Shitposts, err error) {
	_spec := sqlgraph.NewUpdateSpec(shitposts.Table, shitposts.Columns, sqlgraph.NewFieldSpec(shitposts.FieldID, field.TypeString))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Shitposts.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shitposts.FieldID)
		for _, f := range fields {
			if !shitposts.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != shitposts.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Count(); ok {
		_spec.SetField(shitposts.FieldCount, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedCount(); ok {
		_spec.AddField(shitposts.FieldCount, field.TypeInt, value)
	}
	if suo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shitposts.UserTable,
			Columns: []string{shitposts.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shitposts.UserTable,
			Columns: []string{shitposts.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Shitposts{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shitposts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
