// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ritsec/ops-bot-iii/ent/shitposts"
	"github.com/ritsec/ops-bot-iii/ent/user"
)

// ShitpostsCreate is the builder for creating a Shitposts entity.
type ShitpostsCreate struct {
	config
	mutation *ShitpostsMutation
	hooks    []Hook
}

// SetCount sets the "count" field.
func (sc *ShitpostsCreate) SetCount(i int) *ShitpostsCreate {
	sc.mutation.SetCount(i)
	return sc
}

// SetID sets the "id" field.
func (sc *ShitpostsCreate) SetID(s string) *ShitpostsCreate {
	sc.mutation.SetID(s)
	return sc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (sc *ShitpostsCreate) SetUserID(id string) *ShitpostsCreate {
	sc.mutation.SetUserID(id)
	return sc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (sc *ShitpostsCreate) SetNillableUserID(id *string) *ShitpostsCreate {
	if id != nil {
		sc = sc.SetUserID(*id)
	}
	return sc
}

// SetUser sets the "user" edge to the User entity.
func (sc *ShitpostsCreate) SetUser(u *User) *ShitpostsCreate {
	return sc.SetUserID(u.ID)
}

// Mutation returns the ShitpostsMutation object of the builder.
func (sc *ShitpostsCreate) Mutation() *ShitpostsMutation {
	return sc.mutation
}

// Save creates the Shitposts in the database.
func (sc *ShitpostsCreate) Save(ctx context.Context) (*Shitposts, error) {
	return withHooks[*Shitposts, ShitpostsMutation](ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *ShitpostsCreate) SaveX(ctx context.Context) *Shitposts {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *ShitpostsCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *ShitpostsCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *ShitpostsCreate) check() error {
	if _, ok := sc.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "Shitposts.count"`)}
	}
	if v, ok := sc.mutation.ID(); ok {
		if err := shitposts.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Shitposts.id": %w`, err)}
		}
	}
	return nil
}

func (sc *ShitpostsCreate) sqlSave(ctx context.Context) (*Shitposts, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Shitposts.ID type: %T", _spec.ID.Value)
		}
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *ShitpostsCreate) createSpec() (*Shitposts, *sqlgraph.CreateSpec) {
	var (
		_node = &Shitposts{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(shitposts.Table, sqlgraph.NewFieldSpec(shitposts.FieldID, field.TypeString))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.Count(); ok {
		_spec.SetField(shitposts.FieldCount, field.TypeInt, value)
		_node.Count = value
	}
	if nodes := sc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shitposts.UserTable,
			Columns: []string{shitposts.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_shitposts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShitpostsCreateBulk is the builder for creating many Shitposts entities in bulk.
type ShitpostsCreateBulk struct {
	config
	builders []*ShitpostsCreate
}

// Save creates the Shitposts entities in the database.
func (scb *ShitpostsCreateBulk) Save(ctx context.Context) ([]*Shitposts, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Shitposts, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShitpostsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *ShitpostsCreateBulk) SaveX(ctx context.Context) []*Shitposts {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *ShitpostsCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *ShitpostsCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
