name: Run Code Checks

on: [push, pull_request]

permissions:
  contents: read

jobs:
  golangci:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'
          cache: false
      - name: download dependencies
        run: go mod tidy
      - name: Compile
        run: go build main.go
      - name: Unit Tests
        run: go test -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62
          args: --timeout=10m