// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Shitpost is the predicate function for shitpost builders.
type Shitpost func(*sql.Selector)

// Signin is the predicate function for signin builders.
type Signin func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Vote is the predicate function for vote builders.
type Vote func(*sql.Selector)

// VoteResult is the predicate function for voteresult builders.
type VoteResult func(*sql.Selector)
